# Generated by Django 5.2.7 on 2025-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notes",
            field=models.FileField(blank=True, null=True, upload_to="notes/"),
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
